<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Sun0922" failures="1" tests="9" name="org.example.demo111.TestCase.Test01" time="9.858" errors="0" timestamp="07 9æœˆ 2024 02:58:10 GMT" skipped="0">
  <testcase classname="org.example.demo111.TestCase.Test01" name="test6_jf0006_smsCodeSuccess" time="3.013"/>
  <testcase classname="org.example.demo111.TestCase.Test01" name="test1" time="0.179"/>
  <testcase classname="org.example.demo111.TestCase.Test01" name="test7_boc_smsCodefail" time="0.008"/>
  <testcase classname="org.example.demo111.TestCase.Test01" name="test10_demo_post_Json_Success" time="0.108"/>
  <testcase classname="org.example.demo111.TestCase.Test01" name="test4_jf0001" time="3.035"/>
  <testcase classname="org.example.demo111.TestCase.Test01" name="test8_boc_smsCodeSuccess" time="0.007"/>
  <testcase classname="org.example.demo111.TestCase.Test01" name="test6_jf0006_smsCodefail" time="1.031"/>
  <testcase classname="org.example.demo111.TestCase.Test01" name="test3" time="2.468"/>
  <testcase classname="org.example.demo111.TestCase.Test01" name="test11_demo_post_Json_fail" time="0.009">
    <failure message="expected [8888] but found [9999]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [8888] but found [9999]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at org.example.demo111.TestCase.Test01.test11_demo_post_Json_fail(Test01.java:196)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
  </testcase> <!-- test11_demo_post_Json_fail -->
</testsuite> <!-- org.example.demo111.TestCase.Test01 -->
